index:
    path: /
    controller: App\Controller\DefaultController::index
security.login:
    path: /login
    controller: App\Controller\Security\SecurityController::login
security.logout:
    path: /logout
backend:
    prefix: backend/
    name_prefix: 'b_'
    schemes: ['http']
    resource: 'routes/backend.yaml'